; OTA任务配置：填写 task_id 与 version。
; upgrade 为升级任务，downgrade 为降级任务。

[app.upgrade]
; APP升级
task_id=0
version=

[app.downgrade]
; APP降级
task_id=0
version=

[glasses.flow_echo_pilot.bluetooth.upgrade]
; flow_echo_pilot bluetooth 升级
task_id=0
version=

[glasses.flow_echo_pilot.bluetooth.downgrade]
; flow_echo_pilot bluetooth 降级
task_id=0
version=

[glasses.flow_echo_pilot.wifi.upgrade]
; flow_echo_pilot wifi 升级
task_id=0
version=

[glasses.flow_echo_pilot.wifi.downgrade]
; flow_echo_pilot wifi 降级
task_id=0
version=

[glasses.flow_echo_crystal.bluetooth.upgrade]
; flow_echo_crystal bluetooth 升级
task_id=0
version=

[glasses.flow_echo_crystal.bluetooth.downgrade]
; flow_echo_crystal bluetooth 降级
task_id=0
version=

[glasses.flow_echo_crystal.wifi.upgrade]
; flow_echo_crystal wifi 升级
task_id=0
version=

[glasses.flow_echo_crystal.wifi.downgrade]
; flow_echo_crystal wifi 降级
task_id=0
version=

[glasses.flow_pro_pilot.bluetooth.upgrade]
; flow_pro_pilot bluetooth 升级
task_id=0
version=

[glasses.flow_pro_pilot.bluetooth.downgrade]
; flow_pro_pilot bluetooth 降级
task_id=0
version=

[glasses.flow_pro_pilot.isp.upgrade]
; flow_pro_pilot isp 升级
task_id=0
version=

[glasses.flow_pro_pilot.isp.downgrade]
; flow_pro_pilot isp 降级
task_id=0
version=

[glasses.flow_pro_crystal.bluetooth.upgrade]
; flow_pro_crystal bluetooth 升级
task_id=0
version=

[glasses.flow_pro_crystal.bluetooth.downgrade]
; flow_pro_crystal bluetooth 降级
task_id=0
version=

[glasses.flow_pro_crystal.isp.upgrade]
; flow_pro_crystal isp 升级
task_id=0
version=

[glasses.flow_pro_crystal.isp.downgrade]
; flow_pro_crystal isp 降级
task_id=0
version=

[glasses.flow_nova.firmware.upgrade]
; flow_nova firmware 升级
task_id=0
version=

[glasses.flow_nova.firmware.downgrade]
; flow_nova firmware 降级
task_id=0
version=

[glasses.dpvr_g1.bluetooth.upgrade]
; dpvr_g1 bluetooth 升级
task_id=0
version=

[glasses.dpvr_g1.bluetooth.downgrade]
; dpvr_g1 bluetooth 降级
task_id=0
version=

[glasses.dpvr_g1.wifi.upgrade]
; dpvr_g1 wifi 升级
task_id=0
version=

[glasses.dpvr_g1.wifi.downgrade]
; dpvr_g1 wifi 降级
task_id=0
version=

[glasses.dpvr_g3.bluetooth.upgrade]
; dpvr_g3 bluetooth 升级
task_id=0
version=

[glasses.dpvr_g3.bluetooth.downgrade]
; dpvr_g3 bluetooth 降级
task_id=0
version=

[glasses.dpvr_g3.wifi.upgrade]
; dpvr_g3 wifi 升级
task_id=0
version=

[glasses.dpvr_g3.wifi.downgrade]
; dpvr_g3 wifi 降级
task_id=0
version=

[glasses.dpvr_g6.bluetooth.upgrade]
; dpvr_g6 bluetooth 升级
task_id=0
version=

[glasses.dpvr_g6.bluetooth.downgrade]
; dpvr_g6 bluetooth 降级
task_id=0
version=

[glasses.dpvr_g6.wifi.upgrade]
; dpvr_g6 wifi 升级
task_id=0
version=

[glasses.dpvr_g6.wifi.downgrade]
; dpvr_g6 wifi 降级
task_id=0
version=

